import {escapeHtml as e,money,kindNames,roleNames,actionNames,matrixOf,isDone,actorRoles,canWrite} from './domain.js';
import {partiesList} from './parties.js';
import {portfolioPage,objectListPage} from './portfolio.js';
import {conveyorPage} from './conveyor.js';

export function renderWorkspace({ui,data,profile}) {
const btn=(text,action,id='',primary=false)=>`<button ${primary?'class="primary"':''} data-action="${action}" data-id="${e(id)}">${e(text)}</button>`;
const badge=(text,good=false)=>`<span class="badge ${good?'good':''}">${e(text)}</span>`;
const empty=text=>`<div class="empty">${e(text)}</div>`;
const fmtDate=x=>x?new Date(x).toLocaleString('ru-RU',{timeZone:'Europe/Minsk'}):'';
const currentPeriod=()=>data.periods?.find(p=>p.project_id===ui.project);
const editor=(pid=ui.project)=>canWrite(profile,data.memberships,pid);
const canEdit=()=>editor()&&currentPeriod()?.status==='open';
const docs=()=>data.documents.filter(d=>d.project_id===ui.project);
const ver=d=>data.versions.find(v=>v.id===d.current_version);
const projectName=id=>data.projects?.find(p=>p.id===id)?.name||'';
function docTable(list){return list.length?`<div class="table-wrap"><table><thead><tr><th>Документ</th><th>Объект / договор</th><th>Состояние</th><th>Срок</th><th class="num">Рабочая версия, руб.</th><th class="num">Принято, руб.</th></tr></thead><tbody>${list.map(d=>{const v=ver(d),a=data.versions.find(x=>x.id===d.accepted_version),c=data.contracts.find(x=>x.id===d.contract_id);return `<tr><td><button class="link" data-action="doc" data-id="${d.id}">${kindNames[d.kind]} № ${e(d.number)}</button><small>Версия ${v?.version||1}${d.accepted_version&&d.current_version!==d.accepted_version?' · есть изменения':''}</small></td><td>${e(projectName(d.project_id))}<small>${e(c?.number)} · ${c?.direction==='incoming'?'Входящий':'Исходящий'}</small></td><td>${d.workflow_id?`<button class="link" data-action="workflow" data-id="${e(d.workflow_id)}">${badge(d.step_label||'—',isDone(d))}</button>`:badge('Без комплекта')}</td><td>${e(d.due_date||'')}</td>${d.kind==='c29'?'<td class="num muted">—</td><td class="num muted">—</td>':`<td class="num">${money(v?.amount)}</td><td class="num">${a?money(a.amount):''}</td>`}</tr>`;}).join('')}</tbody></table></div>`:empty('В этом месяце документы ещё не созданы.');}
function documentsPage(){return heading('Документы','Состояние документа — шаг его комплекта. Передача, подпись и принятие фиксируются по маршруту комплекта.')+`<section>${docTable(data.documents)}</section>`;}
// Реестр за месяц целиком посчитан в базе (pto_register_matrix): здесь суммы только форматируются.
function matrix(){return matrixOf(data.matrix);}
// Отрицательные собственные силы допустимы (субподряд в ценах предъявления больше выполнения): не блокируются, а подсвечиваются.
const negHint='Собственные силы отрицательны: субподряд больше выполнения по договору';
const ownAttrs=v=>Number(v)<0?` class="num neg" title="${negHint}"`:' class="num"';
const ownBold=v=>Number(v)<0?`<b class="neg" title="${negHint}">${money(v)}</b>`:`<b>${money(v)}</b>`;
function registerPage(){const m=matrix();
 // Оперативная оценка (предварительно) — отдельная колонка, только если она внесена; в итоги «Всего» не входит.
 const hasEstimate=m.rows.some(r=>r.estimate!==null&&r.estimate!==undefined);
 const estimateCell=r=>hasEstimate?`<td class="num muted">${r.estimate!==null&&r.estimate!==undefined?money(r.estimate):''}</td>`:'';
 const basis={acts:' · по актам, С-3а не принята',c3a:' · по С-3а'};
 const amounts=r=>`<td class="num">${money(r.total)}</td>${estimateCell(r)}<td${ownAttrs(r.own)}>${money(r.own)}</td><td class="num">${money(r.subcontract)}</td>${m.columns.map(c=>`<td class="num">${r.cells?.[c.id]?money(r.cells[c.id]):''}</td>`).join('')}`;
 const row=r=>r.kind==='project'?`<tr class="total"><td>Итого по объекту <small>${e(r.project)}</small></td>${amounts(r)}</tr>`:`<tr><td><button class="link" data-action="project" data-id="${e(r.project_id)}">${e(r.project)}</button><small>${e(r.number)} · Итого по договору${basis[r.basis]||''}</small></td>${amounts(r)}</tr>`;
 return heading('Реестр выполнения','Суммы принятых актов. Распределение субподряда — в ценах предъявления заказчику. Договоры и колонки без данных за месяц скрыты.',btn('Excel','export')+btn('Печать','print'))+`<section><div class="table-wrap"><table><thead><tr><th>Объект / договор</th><th class="num">Всего, руб.</th>${hasEstimate?'<th class="num" title="Оперативная оценка до подписания актов">Оценка, предв.</th>':''}<th class="num">Своими силами</th><th class="num">Субподряд</th>${m.columns.map(c=>`<th class="num">${e(c.label)}</th>`).join('')}</tr></thead><tbody>${m.rows.map(row).join('')}${m.rows.length?`<tr class="total"><td>Итого</td>${amounts(m.total)}</tr>`:''}</tbody></table></div>${!m.rows.length?empty('Откройте месяц в карточке объекта.'):''}</section>`;}
function auditPage(){return heading('Журнал изменений','Последние 150 событий по доступным объектам. Время — Минск.')+`<section class="table-wrap"><table><thead><tr><th>Время</th><th>Событие</th><th>Объект</th><th>Пользователь</th><th>Основание</th></tr></thead><tbody>${data.events.map(x=>`<tr><td>${e(fmtDate(x.created_at))}</td><td>${e(actionNames[x.action]||x.action)}</td><td>${e(projectName(x.project_id))}</td><td>${e(data.profiles.find(p=>p.id===x.actor)?.display_name||x.actor)}</td><td>${e(x.detail.reason||x.detail.proof||x.detail.note||'')}</td></tr>`).join('')}</tbody></table></section>`;}
function teamPage(){return heading('Команда','Учётные записи и роли ведёт начальник ПТО. Инженер видит все объекты, а вносит данные по закреплённым. Руководитель только смотрит.')+`<section class="table-wrap"><table><thead><tr><th>Сотрудник</th><th>Роль</th><th>Доступ</th><th>Объекты</th><th></th></tr></thead><tbody>${data.profiles.map(p=>`<tr><td>${e(p.display_name)}</td><td>${e(roleNames[p.role])}</td><td>${p.active?'Активен':'Не активирован'}</td><td>${p.role==='head'?'Все':p.role==='director'?'Просмотр всех':data.memberships.filter(m=>m.user_id===p.id).map(m=>e(projectName(m.project_id))).join(', ')}</td><td>${profile.role==='head'&&p.id!==profile.id?btn('Учётная запись','profile',p.id):''}${profile.role==='head'&&p.role==='engineer'?btn('Назначить объект','member',p.id):''}</td></tr>`).join('')}</tbody></table></section>`;}

const primaryNav=[
 ['today','Сегодня','<path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/>'],
 ['objects','Портфель','<rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/>'],
 ['flow','Подписание','<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M9 3v18M15 3v12"/>'],
 ['register','Реестры','<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M3 15h18M9 3v18"/>'],
 ['help','Справка','<circle cx="12" cy="12" r="10"/><path d="M9.1 9a3 3 0 0 1 5.8 1c0 2-3 2.5-3 4M12 17h.01"/>']
];
const moreNav=[['objectlist','Объекты'],['deadlines','Сроки'],['parties','Контрагенты'],['documents','Документы'],['audit','Журнал изменений'],['team','Команда и права'],['settings','Настройки']];
const icon=path=>`<svg viewBox="0 0 24 24" aria-hidden="true">${path}</svg>`;
const monthLabel=new Date(ui.month+'-01T12:00:00Z').toLocaleDateString('ru-RU',{month:'long',year:'numeric',timeZone:'Europe/Minsk'});
const todayKey=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Minsk',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const readiness=list=>({done:list.filter(isDone).length,total:list.length});
// Задачи не хранятся: это комплекты, на шаге которых действует выбранная роль.
const workflows=()=>data.workflows||[];
const ageDays=w=>{const t=w.last_event_at||w.updated_at||w.created_at;return t?Math.max(0,Math.floor((Date.now()-new Date(t).getTime())/86400000)):0;};
const returned=w=>['return','reset'].includes(w.last_event_kind);
function heading(title,sub,actions=''){return `<div class="heading"><div><h1>${e(title)}</h1><div class="muted">${e(sub)}</div></div><div class="actions">${actions}</div></div>`;}
function ring(done,total,size=64){const pct=total?Math.round(done/total*100):0,r=size/2-7,length=2*Math.PI*r;return `<svg class="ring" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}" role="img" aria-label="Принято документов: ${done} из ${total}"><circle cx="${size/2}" cy="${size/2}" r="${r}" fill="none" stroke="var(--ln)" stroke-width="8"/><circle cx="${size/2}" cy="${size/2}" r="${r}" fill="none" stroke="var(--ac)" stroke-width="8" stroke-linecap="round" stroke-dasharray="${length*pct/100} ${length}" transform="rotate(-90 ${size/2} ${size/2})"/><text x="50%" y="50%" dy=".35em" text-anchor="middle" fill="var(--ink)" font-size="${size/4.2}" font-weight="600">${total?pct+'%':'—'}</text></svg>`;}
function amounts(id){const rows=data.register.filter(r=>!id||r.project_id===id);const total=rows.reduce((s,r)=>s+Number(r.total),0),sub=rows.reduce((s,r)=>s+Number(r.subcontract),0);return {total,sub,own:total-sub};}
function stack({own,sub,total}){return `<div class="stack" role="img" aria-label="Своими силами ${money(own)}, субподряд ${money(sub)} руб.">${total?`<span style="width:${Math.max(0,own)/total*100}%;background:var(--own)" title="Своими силами: ${money(own)} руб."></span><span style="width:${Math.min(100,sub/total*100)}%;background:var(--sub)" title="Субподряд: ${money(sub)} руб."></span>`:''}</div>`;}
const legend=()=>'<div class="legend"><span><i style="background:var(--own)"></i>Своими силами</span><span><i style="background:var(--sub)"></i>Субподряд</span></div>';
// Текущая стоимость и срок договора вычисляются в базе (pto_contract_list) по подписанным допсоглашениям.
const fmtDay=x=>x?new Date(x+'T12:00:00Z').toLocaleDateString('ru-RU',{timeZone:'Europe/Minsk'}):'';
function contractAmount(c){if(c.current_amount===null||c.current_amount===undefined)return '<span class="muted">—</span>';return `${money(c.current_amount)}${c.amount_addendum_number?`<small>по ДС №${e(c.amount_addendum_number)}</small>`:''}`;}
function contractTerm(c){if(!c.current_end_date)return '<span class="muted">—</span>';const late=c.current_end_date<todayKey;return `<span class="pill ${late?'e':''}">${late?'Истёк · ':'до '}${e(fmtDay(c.current_end_date))}</span>${c.term_addendum_number?`<small>по ДС №${e(c.term_addendum_number)}</small>`:''}`;}
function due(d){if(!d.due_date)return '<span class="muted">Без срока</span>';const done=isDone(d),late=!done&&d.due_date<todayKey;return `<span class="pill ${late?'e':done?'g':'w'}">${late?'Просрочен · ':''}${e(new Date(d.due_date+'T12:00:00Z').toLocaleDateString('ru-RU',{day:'numeric',month:'short',timeZone:'Europe/Minsk'}))}</span>`;}
function actionList(list){return list.length?list.slice().sort((a,b)=>(a.due_date||'9999').localeCompare(b.due_date||'9999')).map(d=>`<button class="act" data-action="doc" data-id="${e(d.id)}"><span class="av">${e(projectName(d.project_id).slice(0,1)||'П')}</span><span class="t"><b>${e(d.step_label||'Без комплекта')}</b><small>${e(kindNames[d.kind])} № ${e(d.number)} · ${e(projectName(d.project_id))}</small></span>${due(d)}</button>`).join(''):empty('Нет документов со сроками.');}
function taskList(list,emptyText='Нет комплектов, ожидающих действий.'){return list.length?list.slice().sort((a,b)=>ageDays(b)-ageDays(a)).map(w=>`<button class="act" data-action="workflow" data-id="${e(w.id)}"><span class="av">${e((w.project||'П').slice(0,1))}</span><span class="t"><b>${e(w.template_name)} · ${e(w.step_label)}</b><small>${e(w.project)} · договор № ${e(w.contract_number)} · ${e(w.party||'')}${returned(w)&&w.last_note?` · <span class="neg">возврат: ${e(w.last_note)}</span>`:''}</small></span><span class="pill ${returned(w)?'e':'w'}">${ageDays(w)} дн.</span></button>`).join(''):empty(emptyText);}
function todayPage(){const ready=readiness(data.documents),pending=data.documents.filter(d=>!isDone(d)),late=pending.filter(d=>d.due_date&&d.due_date<todayKey).length;
 // Все шаги отмечает ПТО; комплекты у бухгалтерии показаны отдельно — ПТО ждёт её решения и отмечает его.
 const atPto=workflows().filter(w=>w.actor==='pto'),atAccounting=workflows().filter(w=>w.actor==='accounting');
 const days=Array.from({length:7},(_,i)=>{const date=new Date(todayKey+'T12:00:00Z');date.setUTCDate(date.getUTCDate()+i);const key=date.toISOString().slice(0,10);return {date,key,count:pending.filter(d=>d.due_date===key).length};}),max=Math.max(1,...days.map(d=>d.count));
 return `<h1>Сегодня</h1><div class="muted">${e(new Date().toLocaleDateString('ru-RU',{day:'numeric',month:'long',weekday:'long',timeZone:'Europe/Minsk'}))} · отчётный месяц ${e(monthLabel)} ${late?`<span class="pill e">Просрочено: ${late}</span>`:''}</div>
 <div class="row overview"><div><h2>Выполнение за месяц, ${money(amounts().total)} руб.</h2>${data.projects.length?data.projects.map(p=>`<button class="project-bar" data-action="project" data-id="${e(p.id)}"><span><b>${e(p.name)}</b><span class="muted">${money(amounts(p.id).total)}</span></span>${stack(amounts(p.id))}</button>`).join(''):empty('Добавьте первый объект в портфель, чтобы начать работу.')}${legend()}</div><div class="readiness">${ring(ready.done,ready.total)}<div><b>Принято документов</b><div class="muted">${ready.done} из ${ready.total} за месяц</div></div></div></div>
 <h2>Ближайшие 7 дней</h2><div class="week">${days.map(d=>`<div class="day"><span>${d.count||'—'}</span><div style="height:${d.count?Math.max(8,d.count/max*58):2}px"></div><span>${e(d.date.toLocaleDateString('ru-RU',{day:'numeric',month:'short',timeZone:'Europe/Minsk'}))}</span></div>`).join('')}</div>
 <div class="section-title"><h2>Требует действий ПТО</h2></div>${taskList(atPto,'Нет комплектов, ожидающих действий ПТО.')}
 <div class="section-title"><h2>У бухгалтерии</h2><span class="muted">отметьте принятие или возврат</span></div>${taskList(atAccounting,'В бухгалтерии нет комплектов.')}`;
}
function objectsPage(){return portfolioPage({ui,data,profile,today:todayKey,view:ui.portfolioView==='table'?'table':'tiles'});}
function flowPage(){return conveyorPage({ui,data,profile,month:ui.month});}
function canAct(w){return (actorRoles[w.actor]||[]).includes(profile.role)&&editor(w.project_id)&&data.periods?.find(p=>p.id===w.period_id)?.status!=='closed';}
function projectPage(){const p=currentPeriod(),project=data.projects.find(x=>x.id===ui.project),list=docs(),contracts=data.contracts.filter(c=>c.project_id===ui.project),r=readiness(list),a=amounts(ui.project);let actions='';
 if(!p&&editor())actions+=btn('Открыть месяц','open-period','',true);if(canEdit())actions+=btn('Новый акт','new-doc','',true)+btn('Справка С-3а','new-c3a')+btn('С-29','new-c29')+btn('Оценка выполнения','estimate');
 if(p?.status==='open'&&profile.role==='head')actions+=btn('Проверить','review')+btn('Закрыть период','close');if(p?.status==='closed'&&profile.role==='head')actions+=btn('Открыть повторно','reopen');
 const status=p?(p.status==='closed'?'Период закрыт. Снимок сохранён.':p.reviewed_revision===p.revision?'Период проверен начальником ПТО.':'Период в работе.'):'Отчётный месяц ещё не открыт.';
 const tabs=[['summary','Сводка'],['contracts','Договоры'],['subcontract','Субподряд'],['month','Месяц'],['acts','Процентовки и С-29'],['documents','Документы'],['history','История']];
 const contractTable=`<div class="section-title"><h2>Договоры объекта</h2>${editor()?btn('Добавить договор','new-contract'):''}</div>${contracts.length?`<table><thead><tr><th>Договор</th><th>Направление</th><th>Контрагент</th><th class="num">Стоимость, руб.</th><th>Срок</th></tr></thead><tbody>${contracts.map(c=>`<tr><td><button class="link" data-action="contract" data-id="${e(c.id)}">${e(c.number)}</button></td><td>${c.direction==='incoming'?'Входящий субподряд':'Предъявление заказчику'}</td><td>${e(c.party)}</td><td class="num">${contractAmount(c)}</td><td>${contractTerm(c)}</td></tr>`).join('')}</tbody></table>`:empty('Добавьте договор для подготовки документов.')}`;
 const financial=`<div class="row overview"><div><h2>Выполнение за месяц</h2><div class="amount">${money(a.total)} <span class="muted">руб.</span></div>${stack(a)}${legend()}<div class="amount-details"><span>Своими силами ${ownBold(a.own)}</span><span>Субподряд <b>${money(a.sub)}</b></span></div></div><div class="readiness">${ring(r.done,r.total)}<div><b>Принято документов</b><div class="muted">${r.done} из ${r.total}</div></div></div></div>`;
 let body='';switch(ui.projectTab||'summary'){
 case 'contracts':body=contractTable;break;
 case 'subcontract':body=`<div class="section-title"><h2>Сопоставление субподряда</h2>${canEdit()?btn('Сопоставить субподряд','allocate'):''}</div><p class="muted">Распределение принятых актов в ценах предъявления заказчику.</p>${allocationsTable(data.allocations.filter(x=>x.period_id===p?.id))}`;break;
 case 'month':body=`<div class="banner"><span>${e(status)}</span><span>${e(monthLabel)}</span></div>${financial}${estimatesBlock(ui.project)}<h2>Обязательный комплект: акт, С-3а, С-29</h2>${docTable(list)}`;break;
 case 'acts':body=`<h2>Процентовки и С-29 за месяц</h2>${docTable(list)}`;break;
 case 'documents':body=`<h2>Документы месяца</h2>${docTable(list)}`;break;
 case 'history':body=`<h2>История объекта</h2>${eventTable(data.events.filter(x=>x.project_id===ui.project))}`;break;
 default:body=financial+`<h2>Комплекты месяца</h2>${taskList(workflows().filter(w=>w.project_id===ui.project&&w.actor!=='none'))}`+(!contracts.length?contractTable:'');
 }
 return `<button class="link back" data-action="nav" data-id="objects">← Портфель</button><div class="object-heading"><div><h1>${e(project?.name||'Объект')}</h1><div class="muted">${e(project?.address||'')} ${project?.address?'· ':''}${e(status)}</div></div>${ring(r.done,r.total,56)}</div><div class="tabs" role="tablist" aria-label="Разделы объекта">${tabs.map(([id,label])=>`<button role="tab" aria-selected="${(ui.projectTab||'summary')===id}" class="${(ui.projectTab||'summary')===id?'on':''}" data-action="project-tab" data-id="${id}">${label}</button>`).join('')}</div><div class="actions object-actions">${actions}</div>${body}`;
}
function estimatesBlock(projectId){const rows=matrix().rows.filter(r=>r.kind==='contract'&&r.project_id===projectId&&r.estimate!==null&&r.estimate!==undefined);
 return rows.length?`<h2>Оперативная оценка · предварительно</h2><div class="table-wrap"><table><thead><tr><th>Договор</th><th class="num">Оценка, руб.</th><th class="num">Принято, руб.</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${e(r.number)}</td><td class="num muted">${money(r.estimate)}</td><td class="num">${money(r.total)}</td></tr>`).join('')}</tbody></table></div>`:'';}
function allocationsTable(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>Исходящий акт</th><th>Акт субподрядчика</th><th class="num">В ценах предъявления, руб.</th></tr></thead><tbody>${rows.map(a=>{const out=data.documents.find(d=>d.id===a.outgoing_document),inc=data.documents.find(d=>d.id===a.incoming_document);return `<tr><td>${out?btn(`${kindNames[out.kind]} № ${out.number}`,'doc',out.id):'—'}</td><td>${inc?btn(`${kindNames[inc.kind]} № ${inc.number}`,'doc',inc.id):'—'}</td><td class="num">${money(a.amount)}</td></tr>`;}).join('')}</tbody></table></div>`:empty('Сопоставлений пока нет.');}
function eventTable(events){return events.length?`<div class="table-wrap"><table><thead><tr><th>Время</th><th>Событие</th><th>Пользователь</th><th>Основание</th></tr></thead><tbody>${events.map(x=>`<tr><td>${e(fmtDate(x.created_at))}</td><td>${e(actionNames[x.action]||x.action)}</td><td>${e(data.profiles.find(p=>p.id===x.actor)?.display_name||x.actor)}</td><td>${e(x.detail?.reason||x.detail?.proof||x.detail?.note||'')}</td></tr>`).join('')}</tbody></table></div>`:empty('Событий пока нет.');}
function registersPage(){return registerPage().replace('Реестр выполнения','Реестры')+`<h2>Распределение субподряда</h2>${allocationsTable(data.allocations)}<h2>Готовность месяца</h2><div class="table-wrap"><table><thead><tr><th>Объект</th><th>Проверка ПТО</th><th>Документы</th><th>Период</th></tr></thead><tbody>${data.projects.map(p=>{const period=data.periods.find(x=>x.project_id===p.id),r=readiness(data.documents.filter(d=>d.project_id===p.id));return `<tr><td><button class="link" data-action="project" data-id="${e(p.id)}">${e(p.name)}</button></td><td>${period&&period.reviewed_revision===period.revision?'Проверено':'Не проверено'}</td><td>${r.done} / ${r.total} принято</td><td>${period?.status==='closed'?'Закрыт':period?'В работе':'Не открыт'}</td></tr>`;}).join('')}</tbody></table></div>`;}
function deadlinesPage(){const list=data.documents.filter(d=>!isDone(d));return heading('Сроки','Документы за отчётный месяц, комплекты которых ещё не отмечены как принятые бухгалтерией.')+actionList(list);}
function partiesPage(){return partiesList({data,canEdit:['head','engineer'].includes(profile?.role)});}
function settingsPage(){return heading('Настройки','Тема и размер текста сохраняются в вашем профиле и действуют на любом устройстве.')+`<h2>Тема оформления</h2><div class="theme-options">${[['light','Светлая'],['dark','Тёмная'],['system','Как в системе']].map(([id,label])=>`<button class="theme-option ${ui.theme===id?'on':''}" data-action="theme" data-id="${id}" aria-pressed="${ui.theme===id}"><span class="theme-preview ${id}"><i></i><b></b></span><span>${label}${ui.theme===id?' ✓':''}</span></button>`).join('')}</div><p class="muted">«Как в системе» следует настройке вашего устройства.</p><h2>Размер текста</h2><div class="theme-options">${[[100,'Обычный'],[115,'Крупнее'],[130,'Крупный']].map(([id,label])=>`<button class="theme-option scale-option ${ui.textScale===id?'on':''}" data-action="text-scale" data-id="${id}" aria-pressed="${ui.textScale===id}"><span class="scale-preview" style="font-size:${13*id/100}px">Аа 12 486,91</span><span>${label} · ${id} %${ui.textScale===id?' ✓':''}</span></button>`).join('')}</div><p class="muted">Увеличивает всю страницу, как Ctrl +. Выбор сохраняется в профиле и действует на любом компьютере.</p><h2>Учётная запись</h2><p>${e(profile.display_name)} · ${e(roleNames[profile.role])}</p>${btn('Выйти из системы','logout')}`;}
function helpPage(){return heading('Справка','Работа с объектами и документами.')+`<div class="help-text"><h2>Начало работы</h2><p>Начальник ПТО добавляет объект в разделе «Ещё → Объекты», затем откройте вкладку «Договоры» и создайте договор. Откройте отчётный месяц и добавьте документы.</p><h2>Комплекты и маршруты</h2><p>Документы месяца по договору собираются в комплект автоматически: акты С-2 и справка С-3а — процентовка заказчику, акты субподрядчика — процентовка субподрядчика, С-29 — отдельный маршрут. Комплект движется по шагам; все шаги, включая передачу и принятие бухгалтерией, отмечает ПТО — бухгалтерия системой не пользуется. Переход фиксирует, кому передано и подтверждение; при принятии бухгалтерией — кто принял и отметку о принятии.</p><p>Возврат — на любой предыдущий шаг с причиной и указанием документа с замечанием. Новая версия документа или новый документ возвращают комплект на первый шаг. Бухгалтерия принимает комплект целиком: принятые версии всех документов фиксируются одновременно. Запись о подписи в системе не является электронной подписью.</p><h2>Выполнение и субподряд</h2><p>В реестр входят суммы принятых актов. С-3а и С-29 не увеличивают выполнение повторно. Во вкладке «Субподряд» сопоставьте принятые входящие и исходящие акты в ценах предъявления заказчику.</p><h2>Закрытие месяца</h2><p>Начальник ПТО проверяет комплект документов и закрывает период. Система сохраняет снимок выполнения. Администратор может повторно открыть период с указанием причины.</p><h2>Доступ</h2><p>Учётные записи активирует администратор. Инженеры работают только с назначенными объектами. Доступные действия определяются вашей ролью.</p></div>`;}
function shell(content){const nav=[...primaryNav,...moreNav],title=ui.route==='project'?projectName(ui.project):nav.find(n=>n[0]===ui.route)?.[1]||'Сегодня';
 const railItem=([id,label,path])=>`<button class="nav-item ${ui.route===id||(id==='objects'&&ui.route==='project')?'on':''}" title="${label}" aria-label="${label}" data-action="nav" data-id="${id}">${icon(path)}<span>${label}</span></button>`;
 return `<div id="shell"><aside id="hd" class="${ui.wide?'wide':''}" aria-label="Навигация"><div class="logo" title="Система ПТО">П</div>${primaryNav.map(railItem).join('')}<div class="sp"></div><button class="nav-item ${ui.more||moreNav.some(n=>n[0]===ui.route)?'on':''}" data-action="more" aria-label="Ещё" title="Ещё" aria-expanded="${!!ui.more}">${icon('<circle cx="5" cy="12" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="19" cy="12" r="1.5"/>')}<span>Ещё</span></button><button class="nav-item wb" data-action="wide" title="${ui.wide?'Свернуть':'Подписи'}" aria-label="${ui.wide?'Свернуть':'Подписи'}">${icon('<path d="M13 17l5-5-5-5M6 17l5-5-5-5"/>')}<span>Свернуть</span></button></aside>${ui.more?`<div class="bk" data-action="more"></div><nav class="pop ${ui.wide?'wide-pop':''}" aria-label="Дополнительные разделы">${moreNav.map(([id,label])=>`<button data-action="nav" data-id="${id}">${label}</button>`).join('')}</nav>`:''}<main><header class="top"><div class="crumb">${ui.route==='project'?'<button class="link" data-action="nav" data-id="objects">Портфель</button> / ':''}${e(title)}</div><select id="jump" class="jump" aria-label="Перейти к объекту или разделу"><option value="">Перейти к объекту или разделу</option><optgroup label="Объекты">${data.projects.map(p=>`<option value="project:${e(p.id)}">${e(p.name)}</option>`).join('')}</optgroup><optgroup label="Разделы">${nav.map(([id,label])=>`<option value="nav:${id}">${label}</option>`).join('')}</optgroup></select><input id="month" class="chip" aria-label="Отчётный месяц" type="month" value="${e(ui.month)}"><button class="refresh" title="Обновить данные" aria-label="Обновить данные" data-action="refresh">${icon('<path d="M20 7v5h-5M4 17v-5h5"/><path d="M6 7a7 7 0 0 1 12-2l2 2M4 17l2 2a7 7 0 0 0 12-2"/>')}</button><button class="who" data-action="nav" data-id="settings">${e(profile.display_name)} · ${e(roleNames[profile.role])}</button></header><div class="pg">${content}</div></main></div>`;
}
const pages={today:todayPage,objects:objectsPage,project:projectPage,flow:flowPage,register:registersPage,documents:documentsPage,audit:auditPage,team:()=>teamPage().replace('<h1>Команда</h1>','<h1>Команда и права</h1>'),deadlines:deadlinesPage,objectlist:()=>objectListPage({data,profile}),parties:partiesPage,settings:settingsPage,help:helpPage};
return shell((pages[ui.route]||todayPage)());
}
