import {escapeHtml as e,money,stateNames,kindNames,roleNames,actionNames,registerMatrix} from './domain.js';

export function renderWorkspace({ui,data,profile}) {
const btn=(text,action,id='',primary=false)=>`<button ${primary?'class="primary"':''} data-action="${action}" data-id="${e(id)}">${e(text)}</button>`;
const badge=(text,good=false)=>`<span class="badge ${good?'good':''}">${e(text)}</span>`;
const empty=text=>`<div class="empty">${e(text)}</div>`;
const fmtDate=x=>x?new Date(x).toLocaleString('ru-RU',{timeZone:'Europe/Minsk'}):'';
const currentPeriod=()=>data.periods?.find(p=>p.project_id===ui.project);
const editor=()=>['head','engineer'].includes(profile?.role);
const canEdit=()=>editor()&&currentPeriod()?.status==='open';
const docs=()=>data.documents.filter(d=>d.project_id===ui.project);
const ver=d=>data.versions.find(v=>v.id===d.current_version);
const projectName=id=>data.projects?.find(p=>p.id===id)?.name||'';
function docTable(list){return list.length?`<div class="table-wrap"><table><thead><tr><th>Документ</th><th>Объект / договор</th><th>Состояние</th><th>Срок</th><th class="num">Рабочая версия, руб.</th><th class="num">Принято, руб.</th></tr></thead><tbody>${list.map(d=>{const v=ver(d),a=data.versions.find(x=>x.id===d.accepted_version),c=data.contracts.find(x=>x.id===d.contract_id);return `<tr><td><button class="link" data-action="doc" data-id="${d.id}">${kindNames[d.kind]} № ${e(d.number)}</button><small>Версия ${v?.version||1}${d.accepted_version&&d.current_version!==d.accepted_version?' · есть изменения':''}</small></td><td>${e(projectName(d.project_id))}<small>${e(c?.number)} · ${c?.direction==='incoming'?'Входящий':'Исходящий'}</small></td><td>${badge(stateNames[d.status],d.status==='accepted')}</td><td>${e(d.due_date||'')}</td><td class="num">${money(v?.amount)}</td><td class="num">${a?money(a.amount):''}</td></tr>`;}).join('')}</tbody></table></div>`:empty('В этом месяце документы ещё не созданы.');}
function documentsPage(){return heading('Документы','Передача, получение, подпись и принятие фиксируются отдельно.')+`<section>${docTable(data.documents)}</section>`;}
function matrix(){return registerMatrix(data.register,data.projects,data.contracts,data.documents,data.allocations);}
// Отрицательные собственные силы допустимы (субподряд в ценах предъявления больше выполнения): не блокируются, а подсвечиваются.
const negHint='Собственные силы отрицательны: субподряд больше выполнения по договору';
const ownAttrs=v=>Number(v)<0?` class="num neg" title="${negHint}"`:' class="num"';
const ownBold=v=>Number(v)<0?`<b class="neg" title="${negHint}">${money(v)}</b>`:`<b>${money(v)}</b>`;
function registerPage(){const m=matrix();return heading('Реестр выполнения','Суммы принятых актов. Распределение субподряда — в ценах предъявления заказчику.',btn('Excel','export')+btn('Печать','print'))+`<section><div class="table-wrap"><table><thead><tr><th>Объект / договор</th><th class="num">Всего, руб.</th><th class="num">Своими силами</th><th class="num">Субподряд</th>${m.subs.map(s=>`<th class="num">${e(s)}</th>`).join('')}</tr></thead><tbody>${m.rows.map(r=>`<tr><td><button class="link" data-action="project" data-id="${r.project_id}">${e(r.object)}</button><small>${e(r.number)} · Итого по договору</small></td><td class="num">${money(r.total)}</td><td${ownAttrs(r.own)}>${money(r.own)}</td><td class="num">${money(r.subcontract)}</td>${m.subs.map(s=>`<td class="num">${r.split[s]?money(r.split[s]):''}</td>`).join('')}</tr>`).join('')}<tr class="total"><td>Итого</td>${['total','own','subcontract'].map(k=>{const sum=m.rows.reduce((s,r)=>s+Number(r[k]),0);return `<td${k==='own'?ownAttrs(sum):' class="num"'}>${money(sum)}</td>`;}).join('')}${m.subs.map(s=>`<td class="num">${money(m.rows.reduce((sum,r)=>sum+r.split[s],0))}</td>`).join('')}</tr></tbody></table></div>${!m.rows.length?empty('Откройте месяц в карточке объекта.'):''}</section>`;}
function auditPage(){return heading('Журнал изменений','Последние 150 событий по доступным объектам. Время — Минск.')+`<section class="table-wrap"><table><thead><tr><th>Время</th><th>Событие</th><th>Объект</th><th>Пользователь</th><th>Основание</th></tr></thead><tbody>${data.events.map(x=>`<tr><td>${e(fmtDate(x.created_at))}</td><td>${e(actionNames[x.action]||x.action)}</td><td>${e(projectName(x.project_id))}</td><td>${e(data.profiles.find(p=>p.id===x.actor)?.display_name||x.actor)}</td><td>${e(x.detail.reason||x.detail.proof||x.detail.note||'')}</td></tr>`).join('')}</tbody></table></section>`;}
function teamPage(){return heading('Команда','Учётные записи создаются администратором. Доступ инженеров назначается по объектам.')+`<section class="table-wrap"><table><thead><tr><th>Сотрудник</th><th>Роль</th><th>Доступ</th><th>Объекты</th><th></th></tr></thead><tbody>${data.profiles.map(p=>`<tr><td>${e(p.display_name)}</td><td>${e(roleNames[p.role])}</td><td>${p.active?'Активен':'Не активирован'}</td><td>${['admin','head'].includes(p.role)?'Все':data.memberships.filter(m=>m.user_id===p.id).map(m=>e(projectName(m.project_id))).join(', ')}</td><td>${profile.role==='admin'&&p.id!==profile.id?btn('Учётная запись','profile',p.id):''}${['head','admin'].includes(profile.role)?btn('Назначить объект','member',p.id):''}</td></tr>`).join('')}</tbody></table></section>`;}

const primaryNav=[
 ['today','Сегодня','<path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/>'],
 ['objects','Портфель','<rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/>'],
 ['flow','Конвейер','<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M9 3v18M15 3v12"/>'],
 ['register','Реестры','<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M3 15h18M9 3v18"/>'],
 ['help','Справка','<circle cx="12" cy="12" r="10"/><path d="M9.1 9a3 3 0 0 1 5.8 1c0 2-3 2.5-3 4M12 17h.01"/>']
];
const moreNav=[['deadlines','Сроки'],['parties','Контрагенты'],['documents','Документы'],['audit','Журнал изменений'],['team','Команда и права'],['settings','Настройки']];
const icon=path=>`<svg viewBox="0 0 24 24" aria-hidden="true">${path}</svg>`;
const monthLabel=new Date(ui.month+'-01T12:00:00Z').toLocaleDateString('ru-RU',{month:'long',year:'numeric',timeZone:'Europe/Minsk'});
const todayKey=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Minsk',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const nextLabel={draft:'Передать документ',sent:'Подтвердить получение',received:'Зафиксировать подпись',signed:'Принять бухгалтерией',accepted:'Принято бухгалтерией'};
const readiness=list=>({done:list.filter(d=>d.status==='accepted').length,total:list.length});
function heading(title,sub,actions=''){return `<div class="heading"><div><h1>${e(title)}</h1><div class="muted">${e(sub)}</div></div><div class="actions">${actions}</div></div>`;}
function ring(done,total,size=64){const pct=total?Math.round(done/total*100):0,r=size/2-7,length=2*Math.PI*r;return `<svg class="ring" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}" role="img" aria-label="Принято документов: ${done} из ${total}"><circle cx="${size/2}" cy="${size/2}" r="${r}" fill="none" stroke="var(--ln)" stroke-width="8"/><circle cx="${size/2}" cy="${size/2}" r="${r}" fill="none" stroke="var(--ac)" stroke-width="8" stroke-linecap="round" stroke-dasharray="${length*pct/100} ${length}" transform="rotate(-90 ${size/2} ${size/2})"/><text x="50%" y="50%" dy=".35em" text-anchor="middle" fill="var(--ink)" font-size="${size/4.2}" font-weight="600">${total?pct+'%':'—'}</text></svg>`;}
function amounts(id){const rows=data.register.filter(r=>!id||r.project_id===id);const total=rows.reduce((s,r)=>s+Number(r.total),0),sub=rows.reduce((s,r)=>s+Number(r.subcontract),0);return {total,sub,own:total-sub};}
function stack({own,sub,total}){return `<div class="stack" role="img" aria-label="Своими силами ${money(own)}, субподряд ${money(sub)} руб.">${total?`<span style="width:${Math.max(0,own)/total*100}%;background:var(--own)" title="Своими силами: ${money(own)} руб."></span><span style="width:${Math.min(100,sub/total*100)}%;background:var(--sub)" title="Субподряд: ${money(sub)} руб."></span>`:''}</div>`;}
const legend=()=>'<div class="legend"><span><i style="background:var(--own)"></i>Своими силами</span><span><i style="background:var(--sub)"></i>Субподряд</span></div>';
function due(d){if(!d.due_date)return '<span class="muted">Без срока</span>';const late=d.status!=='accepted'&&d.due_date<todayKey;return `<span class="pill ${late?'e':d.status==='accepted'?'g':'w'}">${late?'Просрочен · ':''}${e(new Date(d.due_date+'T12:00:00Z').toLocaleDateString('ru-RU',{day:'numeric',month:'short',timeZone:'Europe/Minsk'}))}</span>`;}
function actionList(list){return list.length?list.slice().sort((a,b)=>(a.due_date||'9999').localeCompare(b.due_date||'9999')).map(d=>`<button class="act" data-action="doc" data-id="${e(d.id)}"><span class="av">${e(projectName(d.project_id).slice(0,1)||'П')}</span><span class="t"><b>${e(nextLabel[d.status])}</b><small>${e(kindNames[d.kind])} № ${e(d.number)} · ${e(projectName(d.project_id))}</small></span>${due(d)}</button>`).join(''):empty('Нет документов, требующих действий.');}
function todayPage(){const ready=readiness(data.documents),pending=data.documents.filter(d=>d.status!=='accepted'),late=pending.filter(d=>d.due_date&&d.due_date<todayKey).length;
 const days=Array.from({length:7},(_,i)=>{const date=new Date(todayKey+'T12:00:00Z');date.setUTCDate(date.getUTCDate()+i);const key=date.toISOString().slice(0,10);return {date,key,count:pending.filter(d=>d.due_date===key).length};}),max=Math.max(1,...days.map(d=>d.count));
 return `<h1>Сегодня</h1><div class="muted">${e(new Date().toLocaleDateString('ru-RU',{day:'numeric',month:'long',weekday:'long',timeZone:'Europe/Minsk'}))} · отчётный месяц ${e(monthLabel)} ${late?`<span class="pill e">Просрочено: ${late}</span>`:''}</div>
 <div class="row overview"><div><h2>Выполнение за месяц, ${money(amounts().total)} руб.</h2>${data.projects.length?data.projects.map(p=>`<button class="project-bar" data-action="project" data-id="${e(p.id)}"><span><b>${e(p.name)}</b><span class="muted">${money(amounts(p.id).total)}</span></span>${stack(amounts(p.id))}</button>`).join(''):empty('Добавьте первый объект в портфель, чтобы начать работу.')}${legend()}</div><div class="readiness">${ring(ready.done,ready.total)}<div><b>Принято документов</b><div class="muted">${ready.done} из ${ready.total} за месяц</div></div></div></div>
 <h2>Ближайшие 7 дней</h2><div class="week">${days.map(d=>`<div class="day"><span>${d.count||'—'}</span><div style="height:${d.count?Math.max(8,d.count/max*58):2}px"></div><span>${e(d.date.toLocaleDateString('ru-RU',{day:'numeric',month:'short',timeZone:'Europe/Minsk'}))}</span></div>`).join('')}</div>
 <div class="section-title"><h2>Требует действий</h2><span class="muted">${e(roleNames[profile.role])}</span></div>${actionList(pending)}`;
}
function objectsPage(){const cards=data.projects.map(p=>{const period=data.periods.find(x=>x.project_id===p.id),list=data.documents.filter(d=>d.project_id===p.id),r=readiness(list),a=amounts(p.id);return `<button class="tile project-tile" data-action="project" data-id="${e(p.id)}"><div class="tile-head"><div><b>${e(p.name)}</b><small>${e(p.address||'Адрес не указан')}</small></div>${ring(r.done,r.total,56)}</div><div class="tile-total"><span class="muted">За месяц, руб.</span><b>${money(a.total)}</b></div>${stack(a)}<div class="tile-foot"><span class="pill ${period?.status==='closed'?'g':'w'}">${period?.status==='closed'?'Месяц закрыт':period?'Месяц в работе':'Месяц не открыт'}</span><small>${r.done} / ${r.total} документов принято</small></div></button>`;}).join('');
 const table=`<div class="table-wrap"><table><thead><tr><th>Объект</th><th class="num">За месяц, руб.</th><th class="num">Своими силами</th><th class="num">Субподряд</th><th>Документы</th></tr></thead><tbody>${data.projects.map(p=>{const a=amounts(p.id),r=readiness(data.documents.filter(d=>d.project_id===p.id));return `<tr><td><button class="link" data-action="project" data-id="${e(p.id)}">${e(p.name)}</button><small>${e(p.address)}</small></td><td class="num">${money(a.total)}</td><td${ownAttrs(a.own)}>${money(a.own)}</td><td class="num">${money(a.sub)}</td><td>${r.done} / ${r.total} принято</td></tr>`;}).join('')}</tbody></table></div>`;
 return `<div class="view-toggle">${[['tiles','Плитки'],['table','Таблица']].map(([id,label])=>`<button class="${(ui.portfolioView||'tiles')===id?'on':''}" data-action="portfolio-view" data-id="${id}" aria-pressed="${(ui.portfolioView||'tiles')===id}">${label}</button>`).join('')}</div>`+heading('Портфель','Объекты и выполнение за отчётный месяц.',['head','admin'].includes(profile.role)?btn('Добавить объект','new-project','',true):'')+(data.projects.length?(ui.portfolioView==='table'?table:`<div class="grid3">${cards}</div>${legend()}`):empty('Пока нет объектов. Добавьте первый объект для начала работы.'));
}
function flowPage(){const list=data.documents.filter(d=>!ui.flowProject||d.project_id===ui.flowProject),colors=['#dfe5ff','#fde9c2','#d6ecf8','#d3f0e6','#e8e9ee'];return heading('Конвейер месяца','От подготовки ПТО до принятия бухгалтерией.')+`<div class="filter-pills">${[['','Все объекты'],...data.projects.map(p=>[p.id,p.name])].map(([id,label])=>`<button class="${(ui.flowProject||'')===id?'on':''}" data-action="flow-filter" data-id="${e(id)}">${e(label)}</button>`).join('')}</div><div class="kan">${Object.entries(stateNames).map(([state,label],i)=>{const items=list.filter(d=>d.status===state);return `<section class="lane"><div class="lane-title" style="--lane:${colors[i]}"><b>${i===0?'В ПТО':e(label)}</b><span>${items.length}</span></div><div class="lane-sum">${money(items.reduce((s,d)=>s+Number(ver(d)?.amount||0),0))} руб. · все формы</div><div class="col">${items.map(d=>`<button class="card ${d.status==='accepted'?'accepted':d.due_date&&d.due_date<todayKey?'late':'pending'}" data-action="doc" data-id="${e(d.id)}"><b>${e(kindNames[d.kind])} № ${e(d.number)}</b><small>${e(projectName(d.project_id))}</small><div class="card-meta">${due(d)}<small>Версия ${ver(d)?.version||1}</small></div><b>${money(ver(d)?.amount)} руб.</b></button>`).join('')||'<div class="lane-empty">Нет документов</div>'}</div></section>`;}).join('')}</div><p class="muted">Суммы в колонках — контрольные суммы документов. Выполнение по актам смотрите в реестрах.</p>`;}
function projectPage(){const p=currentPeriod(),project=data.projects.find(x=>x.id===ui.project),list=docs(),contracts=data.contracts.filter(c=>c.project_id===ui.project),r=readiness(list),a=amounts(ui.project);let actions='';
 if(!p&&editor())actions+=btn('Открыть месяц','open-period','',true);if(canEdit())actions+=btn('Новый документ','new-doc','',true);
 if(p?.status==='open'&&profile.role==='head')actions+=btn('Проверить','review')+btn('Закрыть период','close');if(p?.status==='closed'&&profile.role==='admin')actions+=btn('Открыть повторно','reopen');
 const status=p?(p.status==='closed'?'Период закрыт. Снимок сохранён.':p.reviewed_revision===p.revision?'Период проверен начальником ПТО.':'Период в работе.'):'Отчётный месяц ещё не открыт.';
 const tabs=[['summary','Сводка'],['contracts','Договоры'],['subcontract','Субподряд'],['month','Месяц'],['acts','Процентовки и С-29'],['documents','Документы'],['history','История']];
 const contractTable=`<div class="section-title"><h2>Договоры объекта</h2>${editor()?btn('Добавить договор','new-contract'):''}</div>${contracts.length?`<table><thead><tr><th>Договор</th><th>Направление</th><th>Контрагент</th></tr></thead><tbody>${contracts.map(c=>`<tr><td>${e(c.number)}</td><td>${c.direction==='incoming'?'Входящий субподряд':'Предъявление заказчику'}</td><td>${e(c.party)}</td></tr>`).join('')}</tbody></table>`:empty('Добавьте договор для подготовки документов.')}`;
 const financial=`<div class="row overview"><div><h2>Выполнение за месяц</h2><div class="amount">${money(a.total)} <span class="muted">руб.</span></div>${stack(a)}${legend()}<div class="amount-details"><span>Своими силами ${ownBold(a.own)}</span><span>Субподряд <b>${money(a.sub)}</b></span></div></div><div class="readiness">${ring(r.done,r.total)}<div><b>Принято документов</b><div class="muted">${r.done} из ${r.total}</div></div></div></div>`;
 let body='';switch(ui.projectTab||'summary'){
 case 'contracts':body=contractTable;break;
 case 'subcontract':body=`<div class="section-title"><h2>Сопоставление субподряда</h2>${canEdit()?btn('Сопоставить субподряд','allocate'):''}</div><p class="muted">Распределение принятых актов в ценах предъявления заказчику.</p>${allocationsTable(data.allocations.filter(x=>x.period_id===p?.id))}`;break;
 case 'month':body=`<div class="banner"><span>${e(status)}</span><span>${e(monthLabel)}</span></div>${financial}<h2>Обязательный комплект: акт, С-3а, С-29</h2>${docTable(list)}`;break;
 case 'acts':body=`<h2>Процентовки и С-29 за месяц</h2>${docTable(list)}`;break;
 case 'documents':body=`<h2>Документы месяца</h2>${docTable(list)}`;break;
 case 'history':body=`<h2>История объекта</h2>${eventTable(data.events.filter(x=>x.project_id===ui.project))}`;break;
 default:body=financial+`<h2>Требует действий</h2>${actionList(list.filter(d=>d.status!=='accepted'))}`+(!contracts.length?contractTable:'');
 }
 return `<button class="link back" data-action="nav" data-id="objects">← Портфель</button><div class="object-heading"><div><h1>${e(project?.name||'Объект')}</h1><div class="muted">${e(project?.address||'')} ${project?.address?'· ':''}${e(status)}</div></div>${ring(r.done,r.total,56)}</div><div class="tabs" role="tablist" aria-label="Разделы объекта">${tabs.map(([id,label])=>`<button role="tab" aria-selected="${(ui.projectTab||'summary')===id}" class="${(ui.projectTab||'summary')===id?'on':''}" data-action="project-tab" data-id="${id}">${label}</button>`).join('')}</div><div class="actions object-actions">${actions}</div>${body}`;
}
function allocationsTable(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>Исходящий акт</th><th>Акт субподрядчика</th><th class="num">В ценах предъявления, руб.</th></tr></thead><tbody>${rows.map(a=>{const out=data.documents.find(d=>d.id===a.outgoing_document),inc=data.documents.find(d=>d.id===a.incoming_document);return `<tr><td>${out?btn(`${kindNames[out.kind]} № ${out.number}`,'doc',out.id):'—'}</td><td>${inc?btn(`${kindNames[inc.kind]} № ${inc.number}`,'doc',inc.id):'—'}</td><td class="num">${money(a.amount)}</td></tr>`;}).join('')}</tbody></table></div>`:empty('Сопоставлений пока нет.');}
function eventTable(events){return events.length?`<div class="table-wrap"><table><thead><tr><th>Время</th><th>Событие</th><th>Пользователь</th><th>Основание</th></tr></thead><tbody>${events.map(x=>`<tr><td>${e(fmtDate(x.created_at))}</td><td>${e(actionNames[x.action]||x.action)}</td><td>${e(data.profiles.find(p=>p.id===x.actor)?.display_name||x.actor)}</td><td>${e(x.detail?.reason||x.detail?.proof||x.detail?.note||'')}</td></tr>`).join('')}</tbody></table></div>`:empty('Событий пока нет.');}
function registersPage(){return registerPage().replace('Реестр выполнения','Реестры')+`<h2>Распределение субподряда</h2>${allocationsTable(data.allocations)}<h2>Готовность месяца</h2><div class="table-wrap"><table><thead><tr><th>Объект</th><th>Проверка ПТО</th><th>Документы</th><th>Период</th></tr></thead><tbody>${data.projects.map(p=>{const period=data.periods.find(x=>x.project_id===p.id),r=readiness(data.documents.filter(d=>d.project_id===p.id));return `<tr><td><button class="link" data-action="project" data-id="${e(p.id)}">${e(p.name)}</button></td><td>${period&&period.reviewed_revision===period.revision?'Проверено':'Не проверено'}</td><td>${r.done} / ${r.total} принято</td><td>${period?.status==='closed'?'Закрыт':period?'В работе':'Не открыт'}</td></tr>`;}).join('')}</tbody></table></div>`;}
function deadlinesPage(){const list=data.documents.filter(d=>d.status!=='accepted');return heading('Сроки','Незавершённые документы за отчётный месяц.')+actionList(list);}
function partiesPage(){const parties=[...new Set(data.contracts.map(c=>c.party))].sort();return heading('Контрагенты','Контрагенты по доступным договорам.')+(parties.length?`<div class="table-wrap"><table><thead><tr><th>Контрагент</th><th>Договоры / объекты</th></tr></thead><tbody>${parties.map(p=>`<tr><td>${e(p)}</td><td>${data.contracts.filter(c=>c.party===p).map(c=>`<div><button class="link" data-action="project" data-id="${e(c.project_id)}">${e(c.number)} · ${e(projectName(c.project_id))}</button></div>`).join('')}</td></tr>`).join('')}</tbody></table></div>`:empty('Контрагенты появятся после добавления договоров.'));}
function settingsPage(){return heading('Настройки','Параметры отображения сохраняются в этом браузере.')+`<h2>Тема оформления</h2><div class="theme-options">${[['light','Светлая'],['dark','Тёмная'],['system','Как в системе']].map(([id,label])=>`<button class="theme-option ${ui.theme===id?'on':''}" data-action="theme" data-id="${id}" aria-pressed="${ui.theme===id}"><span class="theme-preview ${id}"><i></i><b></b></span><span>${label}${ui.theme===id?' ✓':''}</span></button>`).join('')}</div><p class="muted">«Как в системе» следует настройке вашего устройства.</p><h2>Учётная запись</h2><p>${e(profile.display_name)} · ${e(roleNames[profile.role])}</p>${btn('Выйти из системы','logout')}`;}
function helpPage(){return heading('Справка','Работа с объектами и документами.')+`<div class="help-text"><h2>Начало работы</h2><p>В портфеле добавьте объект, затем откройте вкладку «Договоры» и создайте договор. Откройте отчётный месяц и добавьте документы.</p><h2>Движение документов</h2><p>Подготовка ПТО → передача → получение → подпись → принятие бухгалтерией. В карточке документа доступны действия вашей роли, файлы и история версий.</p><p>Передача, получение и подпись фиксируются отдельно с указанием подтверждения. Запись о подписи в системе не является электронной подписью.</p><h2>Выполнение и субподряд</h2><p>В реестр входят суммы принятых актов. С-3а и С-29 не увеличивают выполнение повторно. Во вкладке «Субподряд» сопоставьте принятые входящие и исходящие акты в ценах предъявления заказчику.</p><h2>Закрытие месяца</h2><p>Начальник ПТО проверяет комплект документов и закрывает период. Система сохраняет снимок выполнения. Администратор может повторно открыть период с указанием причины.</p><h2>Доступ</h2><p>Учётные записи активирует администратор. Инженеры работают только с назначенными объектами. Доступные действия определяются вашей ролью.</p></div>`;}
function shell(content){const nav=[...primaryNav,...moreNav],title=ui.route==='project'?projectName(ui.project):nav.find(n=>n[0]===ui.route)?.[1]||'Сегодня';
 const railItem=([id,label,path])=>`<button class="nav-item ${ui.route===id||(id==='objects'&&ui.route==='project')?'on':''}" title="${label}" aria-label="${label}" data-action="nav" data-id="${id}">${icon(path)}<span>${label}</span></button>`;
 return `<div id="shell"><aside id="hd" class="${ui.wide?'wide':''}" aria-label="Навигация"><div class="logo" title="Система ПТО">П</div>${primaryNav.map(railItem).join('')}<div class="sp"></div><button class="nav-item ${ui.more||moreNav.some(n=>n[0]===ui.route)?'on':''}" data-action="more" aria-label="Ещё" title="Ещё" aria-expanded="${!!ui.more}">${icon('<circle cx="5" cy="12" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="19" cy="12" r="1.5"/>')}<span>Ещё</span></button><button class="nav-item wb" data-action="wide" title="${ui.wide?'Свернуть':'Подписи'}" aria-label="${ui.wide?'Свернуть':'Подписи'}">${icon('<path d="M13 17l5-5-5-5M6 17l5-5-5-5"/>')}<span>Свернуть</span></button></aside>${ui.more?`<div class="bk" data-action="more"></div><nav class="pop ${ui.wide?'wide-pop':''}" aria-label="Дополнительные разделы">${moreNav.map(([id,label])=>`<button data-action="nav" data-id="${id}">${label}</button>`).join('')}</nav>`:''}<main><header class="top"><div class="crumb">${ui.route==='project'?'<button class="link" data-action="nav" data-id="objects">Портфель</button> / ':''}${e(title)}</div><select id="jump" class="jump" aria-label="Перейти к объекту или разделу"><option value="">Перейти к объекту или разделу</option><optgroup label="Объекты">${data.projects.map(p=>`<option value="project:${e(p.id)}">${e(p.name)}</option>`).join('')}</optgroup><optgroup label="Разделы">${nav.map(([id,label])=>`<option value="nav:${id}">${label}</option>`).join('')}</optgroup></select><input id="month" class="chip" aria-label="Отчётный месяц" type="month" value="${e(ui.month)}"><button class="refresh" title="Обновить данные" aria-label="Обновить данные" data-action="refresh">${icon('<path d="M20 7v5h-5M4 17v-5h5"/><path d="M6 7a7 7 0 0 1 12-2l2 2M4 17l2 2a7 7 0 0 0 12-2"/>')}</button><button class="who" data-action="nav" data-id="settings">${e(profile.display_name)} · ${e(roleNames[profile.role])}</button></header><div class="pg">${content}</div></main></div>`;
}
const pages={today:todayPage,objects:objectsPage,project:projectPage,flow:flowPage,register:registersPage,documents:documentsPage,audit:auditPage,team:()=>teamPage().replace('<h1>Команда</h1>','<h1>Команда и права</h1>'),deadlines:deadlinesPage,parties:partiesPage,settings:settingsPage,help:helpPage};
return shell((pages[ui.route]||todayPage)());
}
